version: '3.8'

services:
  trading-bot:
    build: .
    container_name: quantfund-trader
    env_file:
      - .env
    volumes:
      # Logs - writable, persisted on host
      - ./logs:/app/logs
      # Data - read-only, contains historical data and models
      - ./data:/app/data:ro
    restart: unless-stopped
    # Keep container running for cron scheduling
    command: tail -f /dev/null
    # Health check inherited from Dockerfile
    healthcheck:
      test: ["CMD", "python", "scripts/health_check.py"]
      interval: 1h
      timeout: 10s
      retries: 3
      start_period: 5s
