version: "3.9"

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantfund-trader
    working_dir: /app
    env_file: .env
    command: ["python", "scripts/run_live.py", "--mode", "paper"]
    environment:
      - PYTHONPATH=/app/src
      - ACCOUNT_TYPE=paper
      - ALPACA_API_KEY_ID=${ALPACA_API_KEY_ID}
      - ALPACA_API_SECRET_KEY=${ALPACA_API_SECRET_KEY}
      - ALPACA_ENDPOINT=https://paper-api.alpaca.markets/v2
    volumes:
      - ./scripts:/app/scripts:rw
      - ./src:/app/src:rw
      - ./configs:/app/configs:rw
      - ./artifacts:/app/artifacts:ro
      - ./logs:/app/logs
      - ./data:/app/data:ro
    healthcheck:
      test: ["CMD-SHELL", "python - <<'PY'\nimport os, sys\nsys.exit(0 if os.path.isdir('/app/logs') else 1)\nPY"]
      interval: "60s"
      timeout: "10s"
      retries: 3
      start_period: "5s"
    restart: unless-stopped
